### ISSUE TITLE
Create OAuth constructor for RestClient

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/alpaca-trade-api-csharp#120]
I'm not seeing the value in requiring me to do something like this:

`_restClient = new RestClient("adsfadsf", "asdfasdf", oauthKey: myAuthKey);`

If the first two parameters are thrown away, why not just have a new constructor for oAuth?

**Comment by OlegRa** [comment]
@codebeaulieu You are right, this should be better for end user but it's not clear for new user what is difference between these two constructors. And it's not clear for compiler which overload should be used if constructor will be called with 2 string parameters without names because existing class has constructor with 5 string parameters (2 mandatory and 3 optional).

I have an idea how to solve all these problems - SDK will use configuration objects instead of constructor arguments. I've already created issue #106 about this change but because it's a breaking change I'm not sure about availability and transition time for it.

As temporary solution we can create simple struct OAuthKey which will hold OAuth key and use it as mandatory parameter in new constructor. In this case we will not break compatibility with existing code and will provide more clear way for new users.

If you OK with this approach (use temporary struct instead of raw string in constructor) I can implement it and include in both 3.3 and 3.2 versions of SDK. But existing approach with named parameter will not be removed for backward compatibility reasons until next major (4.0) release.

**Comment by OlegRa** [comment]
I will close it due two weeks of inactivity. If you @codebeaulieu still want to include it into 3.4.0 or even 3.3.x release feel free to re-open it.
