### ISSUE TITLE
A problem with SockClient, no updates from the websocket

### ISSUE THREAD

**Issue by smartchris84** [alpacahq/alpaca-trade-api-csharp#14]
I've tried to use sockclient to get trade updates from the websocket.

So far, the sockclient is able to get 'Authorized' message from the server but it never receives any trade-related messages whenever a market order is issued.

I tried other Python API(alpaca-trade-api-python) and it worked well using the same API key.

Please help me. 

Thanks.

P.S. The SockClient returns error in Netframework 4.5.2. I temporarily fixed it by manually specifying crypto suites. May need help for this too.

**Comment by OlegRa** [comment]
Problem solved (at least on my PC) in version [1.2.0-alpha](https://www.nuget.org/packages/Alpaca.Markets/1.2.0-alpha) - please, test it and re-open if problem still reproduced. Don't forget - you have to get this version manually because NuGet never update packages to pre-release versions by default.
