### ISSUE TITLE
401 unauthorized on ListDay/MinuteAggregatesAsync()

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/alpaca-trade-api-csharp#15]
I am getting 401 error from `ListDayAggregatesAsync()` using my production key. I have verified this key works in python client. As far as I can tell, `getDefaultPolygonApiQueryBuilder()` is unconditionally setting staging=true

**Comment by OlegRa** [comment]
Problem solved (at least on my PC) in version [1.2.0-alpha](https://www.nuget.org/packages/Alpaca.Markets/1.2.0-alpha) - please, test it and re-open if problem still reproduced. Don't forget - you have to get this version manually because NuGet never update packages to pre-release versions by default.
