### ISSUE TITLE
Explicitly mark all DateTime properties with the Utc suffix

### ISSUE THREAD

**Issue by williamsderek** [alpacahq/alpaca-trade-api-csharp#193]
The latest preview of the C# SDK has a JsonCalendar object that wraps the API results for the calendar endpoint, but it converts the date/time values from EST to UTC and neither the properties nor their tool tips indicate that the source values are being converted from EST to UTC. If a developer looks at the return values in Postman, s/he would assume that the dates are EST. If you are going to convert to UTC, it should probably both indicate in property code comments AND suffixing the property name with UTC to make it clear to the developer. The JsonClock object could also clearly indicate whether it is EST or UTC.

**Comment by OlegRa** [comment]
I've thought about this issue for a while and right now I want to keep all things untouched (as is) and I'll try to explain why.

Since the first release of this SDK, I've worked hard to keep all date-time data in-sync across the whole SDK. Different REST API endpoints return date-time values in different formats (JSON dates, Unix timestamps in seconds/milliseconds) and different time zones (UTC/EST). I've decided to convert all these values into the `DateTime` properties and provide all these properties in the UTC time zone.

Most of such `DateTime` properties have XML comments which state what values are in the UTC time zone (and moreover has `DateTimeKind.Utc` flag). I just assume that such a general-purpose SDK should operate only with UTC date-time values.

I agree with you - it would be more clear for SDK users to have property names that explicitly states that they provide `DateTime` values in the UTC time zone. So my initial thought was: good point, I'll do it. But - this is the breaking change and most of the users hate such breaking changes.

Of course, I can make this transition smooth by marking existing properties as obsolete for the next releases and completely remove them later. But I'm not sure I have time (and willingness) for such massive changes right now.

But this is the open-source software! So if you'll prepare PR with all required changes I'll be glad to review and merge it into the SDK. I'll also change the description of this issue a little bit and make it more generic.

**Comment by williamsderek** [comment]
Considering the circumstances you describe, I think it would probably be enough to just properly document the properties (XML comments) for DateTime member especially to indicate UTC across the project so that tooltips will consistently show the pattern to users. It is sort of odd that since the SDK appears to be oriented around the US markets based on the fact that the calendar object only returns US market times in EST yet the SDK itself converts everything to a different time zone. But I also understand how the .NET framework tropes toward using a universal time such as UTC.  The key then is to make it as easy as possible for developers to use a single time zone for all operations.  And then documentation for the SDK would do well to include a best practice for using UTC across the board for all market operations. And yes, one of the considerations certainly is that the conversion from Unix time appears to manifest by default in UTC as well.
I will see about putting together a PR with code comments in appropriate classes aimed at clearly indicating a consolidated and consistent pattern of using UTC for all market operations.
