### ISSUE TITLE
Aggregate Query Error

### ISSUE THREAD

**Issue by FranMaher** [alpacahq/alpaca-trade-api-csharp#194]
I am trying to request aggregate data with the latest API version using .NET 4.8
Could not create an instance of type Alpaca.Markets.JsonHistoricalItems`2[Alpaca.Markets.IAgg,Alpaca.Markets.JsonPolygonAgg]. Type is an interface or abstract class and cannot be instantiated. Path 'ticker', line 1, position 10.

**Comment by OlegRa** [comment]
@FranMaher You should never treat the `develop` branch as 'latest API version' - it's just a 'work in progress' and mostly unstable and possibly not working development experiments area. It's especially true right after merging from this branch into the `master` branch in the scope of the official public release process.
I recommend you consuming this SDK in the form of the NuGet package instead of building it from sources. But of course, you can do it as you wish (it's open-source at the end of all) - just remember about the stability model - the `master` branch is very stable (I hope) and the `development` branch is very unstable and changed often.
By the way, I've fixed the problem that you've found in the `development` branch. It's not visible for my tests because they based on the NuGet packages and nobody who use SDK in this way affected by this problem.

**Comment by OlegRa** [comment]
@FranMaher Please, pull updated sources, test and close if the problem fixed.

**Comment by FranMaher** [comment]
Ok, I'll use NuGet know that I know.  I was directed to the development branch when I clicked on the C# API link provided by the Alpaca website.
