### ISSUE TITLE
ListHistoricalTradesAsync function in Alpaca.Markets/PolygonDataClient.cs doesn't work

### ISSUE THREAD

**Issue by aliasgharrajabi** [alpacahq/alpaca-trade-api-csharp#197]
I have been trying to fetch historical trades into my algorithm using Alpaca.Markets/PolygonDataClient.cs and it looks like it returns no value.
Has anyone come across the same issue?

**Comment by OlegRa** [comment]
@aliasgharrajabi Could you please provide minimal code example which reproduces this problem? I assume that you use the stable 3.6.1 version of SDK via NuGet and you have a trading account (not paper one) because the paper accounts have no Polygon.io connectivity.

**Comment by aliasgharrajabi** [comment]
Thanks a lot @OlegRa for following up so quickly.
Well I am using QuantConnect and they have recently updated Alpaca SDK.
I also have a funded live trading account and the result is the same on both live and paper account.
To be more specific, when [this line](https://github.com/QuantConnect/Lean/blob/master/Brokerages/Alpaca/AlpacaBrokerage.Utility.cs#L288)  gets executed, it calls [ListHistoricalTradeAsync](https://github.com/QuantConnect/Lean/blob/master/Brokerages/Alpaca/Markets/PolygonDataClient.cs#L100) function and it can't get the historical trades.

After more testings over the past few hours I realized that the endpoint on [polygon's website](https://polygon.io/docs/#get_v2_ticks_stocks_trades__ticker___date__anchor) doesn't work either, at least not for the symbols I used and the page went unresponsive completely.

**Comment by OlegRa** [comment]
@aliasgharrajabi I've checked the QuantConnect/Lean repo and looks like 28 days ago it was [updated](https://github.com/QuantConnect/Lean/pull/4195) with close-to-latest sources from this repo (thanks to @gsalaz98). In any case if you have troubles with QuantConnect - open issues in their repo because they use this SDK in the form of source code porting not via NuGet and all issues should be addressed to them directly.
