### ISSUE TITLE
No Client OrderId?

### ISSUE THREAD

**Issue by pratttrader** [alpacahq/alpaca-trade-api-csharp#198]
So I'm upgrading from 3.5.5 to 3.6.1 and you've moved to using NewOrderRequest with PostOrderAsync.  But I notice that you don't have a parameter for a user supplied client orderId and instead you're returning the auto-generated orderId.  Is this on purpose?    Am I missing something here?  Also, I see there is an overloaded version of PostOrderAsync...is that just the deprecated version where all params are passed directly?  Thanks.

**Comment by pratttrader** [comment]
Nevermind...I got my answers.

**Comment by pratttrader** [comment]
So I guess my updated question would be: is there an architectural reason why you didn't include more optional parameters in the constructor of NewOrderRequest() for all additional properties beyond .duration?  It seems quite a few people create their own orderId on the client side and pass to Alpaca, so having ClientOrderId would be a nice addition, but not a game breaker.  But maybe there's a reason you didn't do that.

**Comment by OlegRa** [comment]
@pratttrader The reason is simple. In most cases, you have mandatory and optional fields. 

Mandatory fields configured via constructor because it's the simplest way for checking at compile time that users at least try to provide some values for these fields. I know that this check is not enough and that's a reason why we have validation for parameters passed into the constructor.

In previous versions of SDK, we use mandatory and optional arguments for methods but this approach has some drawbacks. If we add some fields into the SDK we have to add a new optional field into the end of the arguments list because instead, we (potentially) will break existing code. And long lists of arguments for methods are hard to understand and use.

And finally, a little bit about client order id. Each order has two identifiers - the `OrderId` is an auto-generated identifier, assigned to each order by the server. Users are unable to specify it and unable to change it. Moreover you unable to predict it on initial order placement. That's a reason why each order also has the `ClientOrderId` identifier. But not this identifier is optional and in many cases, you don't need it at all.

**Comment by OlegRa** [comment]
@pratttrader And of course you can always use C# object initializers for creating the instance of `NewOrderRequest` object in this way:

```cs
var clientOrderId = Guid.NewGuid().ToString("N");
var order = await client.PostOrderAsync(
    new NewOrderRequest("SPY", 100, OrderSide.Buy, OrderType.Market, TimeInForce.Gtc)
    {
        ClientOrderId = clientOrderId
    });
```

**Comment by pratttrader** [comment]
I guess when I design my classes I always put all mandatory and optional parameters in the constructor so I know what is available.  The only reason I knew that you had a ClientOrderId property available is because I dug through your class implementation and found it.  But obviously if the SDK is a fluid architecture, I understand your reasoning.   The reason I use my own Id is because before an order is even submitted, I do a lot of pre-processing on my side and capture "state" data in a db for later analysis and use my user created ID for all of that.   And then when a trade comes back as filled, everything is linked.  There are other ways to do it, but  I also use my system with other brokers and they implement Ids differently.  Thanks !!
