### ISSUE TITLE
Polygon API not supported for Paper Environment

### ISSUE THREAD

**Issue by samueldonovan1701** [alpacahq/alpaca-trade-api-csharp#216]
When attempting to use `Alpaca.Markets.Environments.Paper.GetPolygonStreamingClient()` or `GetPolygonDataClient()` an error is thrown stating that Polygon API is not available for the Paper environment. This is probably due to `Alpaca.Markets.Environments.Paper.PolygonStreamingApi` being undefined. 

This is likely in place due to the data is not being available to users who have not yet set up live accounts, as stated [here](https://alpaca.markets/docs/api-documentation/api-v2/polygon-integration/). However, as developer, I find this rather inconvenient as it necessitates me using both the `Paper` and `Live` environments when I want to make Paper transactions based on data from Polygon, which offers more information as compared to the `AlpacaDataClient`.

I don't imagine any problems would occur when adding support, as users without live accounts would most likely receive a `401 - Unauthorized` response, and therefore a failed `AuthStatus` when attempting to use the  Polygon Data Client.

**Comment by OlegRa** [comment]
@samueldonovan1701 I want to explain to you my vision first and later I'll provide you options for solving your issue.

Which values do you suggest to provide for the `PolygonDataApi` and `PolygonStreamingApi` properties of the `PaperEnvironment` class? The proper URLs of the live environment? Of course, it will solve your problem but it will create unnecessary workload on Alpaca and Polygon servers. Moreover - for other SDK users it will remove the `red flag` signaled as soon as possible and they will start asking about 'authorization' problems.

Designing the SDK is not so easy. In general, each public API design is a set of compromises. The initial versions of SDK just expect that the user will provide a URL for connecting to the proper environment in the client class constructor. But many users have had problems with connecting to any environment except the default one.

That was a primary reason for me to introduce helper classes for simplifying handling different environments in the code. I prefer 'fail fast' approach for handling the incorrect states in code. Ideally, you should not able to create `PolygonDataClient` or 'PolygonStreamingClient` class instances connected to the paper environment. It should be not possible at the compiler level. And I know how to do it but I've decided to make things more flexible and move this check to the run time.

I hope you understand my position and as a bonus point, I'll provide you some ideas about how to handle this issue in your code:

1. The most convenient approach - implement your versions of the `PaperEnvironment` and `LiveEnvironment` classes. The SDK helper classes never use these classes directly - instead, they use the `IEnvironment` interface and you can provide your implementation of this interface on your side and use these implementations instead of built-in ones. You can check the `Staging` class from my [SDK testing repo](https://github.com/OlegRa/Alpaca.Markets.Tests/blob/develop/Alpaca.Markets.Tests/Staging.cs) as a base point for your implementation.
2. The least convenient approach - make your own copy or even fork of SDK and apply required changes. But be ready for applying all future modifications to your fork/copy.

**Comment by samueldonovan1701** [comment]
@OlegRa I think you're reasoning here is sound, and I appreciate both your response and suggestions.

In retrospect, I think your "Fail Fast" approach here is a valid: While I recognized the fact that such a change would put a larger load on the servers, I didn't imagine it would be significant. 
My initial, rather unmeditated concern stemmed from paranoia around an interface method being inherently unimplemented (I think that hits multiple points in the SOLID principles). However, based on what I comprehend, I think the decision made here was sensible.

I agree with, and will implement your first suggestion as a solution.

Thanks again!
