### ISSUE TITLE
Keeping DataStreamingClient WebScoket connection alive 

### ISSUE THREAD

**Issue by Huios** [alpacahq/alpaca-trade-api-csharp#222]
When using Alpaca.Markets.AlpacaDataStreamingClient to subscribe to a data stream, the websocket connection eventually closes after a while (due to the nature of the websocket protocol). If one needs to keep the connection alive, one way to get around this would be to send a heartbeat/ping the server. Is there an inbuilt way to do this?
In addition, is there a way to detect when a websocket connection drops so as to reconnect and resubscribe?

Thanks!

**Comment by OlegRa** [comment]
@Huios The default WebSocket connector used by the SDK is WebSoket4Net and it by default sends/receives ping messages over the WS connection for preventing disconnections.

Most probably the root cause of your disconnections is something else. You can subscribe to the `OnError` event - some network-related errors are reported via this event.

If you want to implement your own reconnect logic just use `SocketOpened`/`SocketClosed` events pair and handle it according to your reconnection strategy.

**Comment by Huios** [comment]
Thanks Oleg, that helps!
