### ISSUE TITLE
Feature Request: Allow a list of symbols for subscribe methods in Alpaca Data Streaming Client

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#234]
I would like to request the various subscribe methods in the alpaca data streaming client to match with the polygon data streaming client as in how they can accept a single symbol or a list of symbols.

**Comment by OlegRa** [comment]
@ooples Due to some internal design reasons I'm unable to add this feature directly into the `AlpacaDataStreamingClient` class. But I can implement it as set of extensions methods for the base `IAlpacaDataStreamingClient` interface. Please, try these methods in the latest [3.9.0-beta1](https://www.nuget.org/packages/Alpaca.Markets/3.9.0-beta1) version of SDK, and if they work as you expected I'll backport them into the 3.8.x too.

**Comment by ooples** [comment]
I tested out your new extension methods but it only seems to work for the first item in the list you pass it and it has slowed the feed to a crawl. I have sent you code so you can verify on your end.

**Comment by OlegRa** [comment]
@ooples I've checked your (and my) code and I have some comments:

1. There is some implementation issue in my extension methods (and base class) - I will fix it in the upcoming release after testing.
2. Besides this implementation problem - it's not a good idea to subscribe to ALL active contracts for ALL possible events. At one hand - Alpaca streaming API limits the number of active quote and trade subscriptions per connection, and at another hand (and maybe it's the main reason for the previous limit) - think about your network bandwidth.

I suggest you rewrite your example and filtering contracts down to manageable (and supported by Alpaca) numbers. And you can subscribe to minute bars for ALL active contracts just by calling `GetMinuteAggSubscription` method without any arguments.

**Comment by ooples** [comment]
I look forward to the changes you make and I will test them for you when you are finished. My idea was to go with the max limit of what a normal user might do to push the api to it's limit and see what it could handle for testing. I didn't intend for my final example code to go to those extremes but it is handy to know about the GetMinuteAggSubscription without any arguments because I wasn't previously aware of that functionality.

**Comment by OlegRa** [comment]
@ooples Please, try the version [3.9.0-beta2](https://www.nuget.org/packages/Alpaca.Markets/3.9.0-beta2) for updated multi-asset subscription teting.

**Comment by ooples** [comment]
The new version is working for the most part but there is a bug that I have found if you use the full active symbols list it closes the connection but if you take the first 100 symbols from that list for example it gives you a proper error message that you can only subscribe to a max of 30 symbols. I will send you the code so you can see for yourself

**Comment by OlegRa** [comment]
@ooples I'm not sure that SDK should prevent ALL possible invalid use cases. Again, subscribing trades for ALL active instruments is a VERY bad idea in general and it doesn't matter how exactly the application will fail. Socket connection closed by the server-side due to the incoming message size limit hitting. I'll add some guards in the extension methods in the upcoming release but it will just prevent huge subscription attempts and do not solve the problem with big messages in general.

I suggest closing this issue because in general, it works as expected (with known server-side limitations). I'm pretty sure that nobody will try to subscribe to trades/quotes for ALL assets in any real application.
