### ISSUE TITLE
How to gracefully recover from Bad Gateway (and other related errors)?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#236]
I have encountered BadGateway in the middle of my live algo trading couple of times. I am currently using NuGet version 3.9.0-beta1 but when the error was countered I was using 3.8.1. Here is what I was doing.

1. I kick off my algo trading application with above nuget package on Saturday morning (when markets are closed). So it is basically awaiting the market to open (based on the sample code at https://github.com/alpacahq/alpaca-trade-api-csharp/blob/develop/UsageExamples/MeanReversionBrokerage.cs).

2. The code works as expected. When the market opens on Monday morning, it goes into my algo trading as expected.

3. In the middle of the trading day on Monday, I randomly get a Bad Gateway error while the application is trying to get a list of orders for a given symbol. It does not happen all the time.

4. I am using following code snippet to create my trading client:
```
	IAlpacaTradingClient tradingClient = Environments.Live.GetAlpacaTradingClient(new OAuthKey(accessToken));
```

5. In cloud environments, one has to take control of connection errors (such as Bad Gateway, connection resets etc.). Therefore the above way of creating a trading client is not enough to handle these errors.

6. So I modified creation of trading client to following:
```
	var tradingClientConfig = new AlpacaTradingClientConfiguration()
	{
		ApiEndpoint = Environments.Live.AlpacaTradingApi,
		SecurityId = new OAuthKey(accessToken),
		HttpClient = new HttpClient()
	};
	IAlpacaTradingClient tradingClient = new AlpacaTradingClient(tradingClientConfig);
```

7. This gives me control of HttpClient creation. But it is still not enough to intercept Bad Gateway errors and retry the connection transparent to my algo logic.

8. So I modified the code further to following naive custom HttpClientHandler implementation and retries BadGateway error for 3 times.
```
	var tradingClientConfig = new AlpacaTradingClientConfiguration()
	{
		ApiEndpoint = Environments.Live.AlpacaTradingApi,
		SecurityId = new OAuthKey(accessToken),
		HttpClient = new HttpClient(new MyAlpacaClientHandler())
	};
	IAlpacaTradingClient tradingClient = new AlpacaTradingClient(tradingClientConfig);
	
	//Custom HttpClientHandler implementation
    public class MyAlpacaClientHandler : HttpClientHandler
    {
        const int MaxAttempts = 3;

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var currentAttempt = 0;
            HttpResponseMessage response = null;

            while (currentAttempt < MaxAttempts)
            {
                response = await base.SendAsync(request, cancellationToken);

                if (response.IsSuccessStatusCode)
                {
                    break;
                }

                if (response.StatusCode == System.Net.HttpStatusCode.BadGateway)
                {
                    currentAttempt++;
                    Console.WriteLine($"--------- {DateTime.Now} BadGateway error encountered. Retry attempt: {currentAttempt} ---------");
                }
                else
                {
                    break; //Do not retry other errors.
                }
            }

            return response;
        }
    }
```

9. The above code seem to be working in my test environment.

**Questions:**
1. Why do I get Bad Gateway error?
2. Is having a customer handler, the correct way to handle the BadGateway (with respect to Alpaca APIs)? Or is there a better way?
3. Are there any other errors that I should be looking out for?

**Comment by rudeGit** [comment]
Posted question about http status codes in Alpaca forums at https://forum.alpaca.markets/t/question-about-http-status-codes-503-and-429/2795

**Comment by OlegRa** [comment]
@rudeGit First, I'll answer your questions about the `HttpClient` errors handling:

1. I don't know exactly why do you receive the HTTP 502 (Bad Gateway) error. In most cases, this error related to changes in the HTTP proxies chain or IP address of underlying API server changes. I strongly recommend you to use the `IHttpClientFactory` class for creating new instances of the `IHttpClient` class because this factory handles a lot of HTTP-related issues for long-running applications like back-end servers.
2. Your approach looks good but in fact, it duplicates existing logic already built-in into SDK for a while. Check the `ThrottlingParameters` property of the `AlpacaTradingClientConfiguration` class. This configuration object contains some properties for tweaking HTTP request repeating logic and it includes the `RetryHttpStatuses` property that allows you to add more HTTP status codes into the existing throttling and call repetitions logic.
3. I don't know - existing throttle handles several headers/status codes that well documented by Alpaca. For me, it's better to handle more specific errors at the caller site via exceptions handling but if you want you can use your approach or the `ThrottlingParameters` configuration object.

And now about your forum question - this SDK uses built-in .NET properties for handling the `Retry-After` HTTP header. See more details in the `RateThrottler.CheckHttpResponse` method [implementation](https://github.com/alpacahq/alpaca-trade-api-csharp/blob/db8a9bea6f81d901b18e6f713b301b8c1505184e/Alpaca.Markets/Throttling/RateThrottler.cs#L194).

**Comment by rudeGit** [comment]
@OlegRa Interesting. I also looked at IThrottler implementation in the above link. Could you have benefitted from Polly library (https://github.com/App-vNext/Polly) for some of this code? Or was it too much to work with Polly for rate limiting stuff?

**Comment by OlegRa** [comment]
@rudeGit Initial idea behind this SDK was to limit the number of dependencies as much as possible and it's the reason why this rate-limiting staff was implemented internally. It's not easy to add Polly library support into the existing solution without breaking the backward compatibility. I'll open a new issue and target it to the next major release - maybe it's a good time for using something more stable and configurable than just a current naive implementation. I should think about all procs and cons and it's not a task for the current minor release definitely.
