### ISSUE TITLE
Allow alpaca streams to be disconnected manually

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#273]
If you want to disable the alpaca streams manually and you have the WithReconnect setup, then you have no easy way to disconnect the alpaca streams because they will keep attempting reconnects.

**Comment by OlegRa** [comment]
@ooples Could you please provide more information about this problem. I've checked the code and all looks fine for me - if you call the `Dispose` or `DisconnectAsync` method reconnection process should stop. Some incoming messages can arrive after this call due to the asynchronous message processing approach but in general after these calls no more reconnections should happen. If you can create a simple project with minimal code for reproducing this issue (ideally some console app) it would be helpful.

**Comment by ooples** [comment]
I sent you an email with working code

**Comment by OlegRa** [comment]
@ooples I've checked your code and I see the root cause of your problem (I hope). You use the `WithReconnect` extension method incorrectly - you should not just call it, but save a result of this call and use it instead of an original client interface instance. For example, instead of your code (simplified version):

```cs
polygonStreamingClient = Environments.Live.GetPolygonStreamingClient(LIVE_API_KEY);
// implements reconnection logic for when a socket is closed unexpectedly
PolygonStreamingClientExtensions.WithReconnect(polygonStreamingClient, new ReconnectionParameters()
    { MaxReconnectionAttempts = 10000});
```

You should write something like this:


```cs
polygonStreamingClient = Environments.Live.GetPolygonStreamingClient(LIVE_API_KEY);
// implements reconnection logic for when a socket is closed unexpectedly
polygonStreamingClient = PolygonStreamingClientExtensions.WithReconnect(
    polygonStreamingClient, new ReconnectionParameters() { MaxReconnectionAttempts = 10000});
```

Or even in more simple form:

```cs
polygonStreamingClient = Environments.Live.GetPolygonStreamingClient(LIVE_API_KEY);
// implements reconnection logic for when a socket is closed unexpectedly
polygonStreamingClient = polygonStreamingClient.WithReconnect(new ReconnectionParameters()
    { MaxReconnectionAttempts = 10000});
```

The `WithReconnect` method returns a new instance of the original interface class and you have to use this new instance for all subsequent calls (including the `DisconnectAsync` and the `Dispose` methods calls). In your case, this new instance just created but you unable to use it because the reference is not stored in any named variable. But it will survive all GCs until you free all references on the original `polygonStreamingClient` variable because this wrapper subscribes to this instance events.

You can read more about the expected way of these extension methods usage patterns in code on the [Wiki](../wiki/Extensions-Package#auto-reconnection-support) page.
