### ISSUE TITLE
Any example of adding ticker symbol to Watchlist will be very helpful

### ISSUE THREAD

**Issue by mehtadharmesh** [alpacahq/alpaca-trade-api-csharp#279]
I am not sure how to create ChangeWatchListRequest / how to pass parameter to AddAssetIntoWatchListByNameAsync function.
Not sure about TKey stuff. any help is really appreciated.

```cs
private async Task<bool> AddStockToWatchList(string aWatchListName, string aTickerSymbol)
{
    bool b = true;
    bool found = false;

    try
    {
        var watchlist1 = await Util.mAlpacaTradingClient.GetWatchListByNameAsync(aWatchListName);
        found = true;

        /** ChangeWatchListRequest openWith = ("MY_WATCHLIST" , "INTC"); **/

        Util.mAlpacaTradingClient.AddAssetIntoWatchListByNameAsync(openWith); 
    }
    catch (Exception)
    {
        found = false;
    }

    return b;
}
```

**Comment by OlegRa** [comment]
@mehtadharmesh The simplest way for finding the usage examples is by checking the test code. You can see all Watchlist-related methods usage in this [test class](https://github.com/OlegRa/Alpaca.Markets.Tests/blob/develop/Alpaca.Markets.Tests/AlpacaTradingClientTest.WatchList.cs) code.

In fact, you can reference your watchlist by name or by identifier. In the first case, you use overloads/generics with the `String` type and in the second case with the `Guid` type.

In your particular case commented line should look like this:

```cs
var openWith = new ChangeWatchListRequest<String>(aWatchListName, aTickerSymbol));
```

And I strongly recommend you to use the `ListWatchListsAsync` method for getting the full list of watchlist associated with the account instead of requesting it by name and handling the exception.

Please, close this issue if you have no more questions related to the SDK usage for watchlists' management.

**Comment by mehtadharmesh** [comment]
Thank you so much, and I really appreciate your prompt response, very impressed with the marvelous work offered to the community.
