### ISSUE TITLE
Use unsigned types for quantities, volumes, etc.

### ISSUE THREAD

**Issue by gjtorikian** [alpacahq/alpaca-trade-api-csharp#283]
Usually around responses around volume, signed data types are used. For example:

https://github.com/alpacahq/alpaca-trade-api-csharp/blob/a3c9c3f25f166cb0921a66f2fbb0824d31ea5047/Alpaca.Markets/Interfaces/IAggBase.cs#L35

Int64 is of the range `-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807`; so far as I know, the API shouldn't ever be able to return a negative volume.

Would you accept a PR that converts these data types to their unsigned types, eg Uint64?

**Comment by OlegRa** [comment]
@gjtorikian The idea, in general, is very good but I have some concerns:

1. This is the breaking change and most of the users strongly dislike the breaking changes. We can do it in step-by-step basic as I've made it for similar changes in API but it will be too long and too expensive (in terms of support/maintenance time).
2. The unsigned types are not CLR-compatible and theoretically, it can introduce some problems for .NET users who use not a C#/VB.NET as their primary development languages. But I'm sure we can just ignore this compatibility nowadays.

So, I'm OK with proposed changes if they will meet the next conditions:

- You will split your changes by sets of PRs for independent areas - at least for Alpaca trading/data REST API types and for Alpaca/Polygon streaming types. It will make the review process easier and will prevent us from an all-or-none acceptance problem.
- You will prepare these PRs for the `develop` branch because right now upcoming 5.0 version in any case brakes many API conventions and we can introduce such breaking changes easily.

**Comment by gjtorikian** [comment]
Works for me! 

Do you have a timeline for when 5.0 will be stable? I see it's still in alpha. I would like to get this change in (but not at the risk of other work, I unfortunately have a day job 😅).

**Comment by OlegRa** [comment]
@gjtorikian I have plans to release the final version of 5.0 in 2-3 months but most of the really breaking changes already in development so I expect more-or-less stable interfaces at end of the March. I hope this timeline is OK for you. You can always track release progress using [this](../milestone/12) web page (I use milestones instead of projects for this repo for historical reasons).

**Comment by gjtorikian** [comment]
Oh that's perfect. Thanks for agreeing to this change, I'll get right on it, starting small at first.
