### ISSUE TITLE
transfer PolygonDataClient and PolygonStreamingClient to polygon.io?

### ISSUE THREAD

**Issue by jeffwlandry** [alpacahq/alpaca-trade-api-csharp#284]
6 days is a very short transition window, especially when the new api is apparently undefined or available.

Has Alpaca considered giving the alpca c# polygon api code to Polygon.io so existing Alpaca users can transition merely by using their polygon key instead of their alpaca key?

Thank you,
jeff

**Comment by OlegRa** [comment]
@jeffwlandry At first, I'm not a full-time Alpaca employee so these upcoming changes are surprised me as well.

But fortunately, this SDK is open-sourced so you have plenty of options:

1. You can get code from SDK, remove all Alpaca-related staff, change Polygon.io authorization logic and use this code as-is for your own project.
2. You can go further and publish the result of your derivative work as an independent Polygon.io client in the .NET ecosystem.

Both options are valid because this code published under the MIT license. You just have to specify the origins of the ported code. 

In fact, about 9 months ago I've started a separate project for providing full Polygon.io .NET SDK here on GitHub - [Polygon.Client](https://github.com/OlegRa/Polygon.Client). Unfortunately, I did not so much progress in it because I'm not sure this effort worth it.

If you don't want to do all this stuff by yourself you can hire me on [UpWork](https://www.upwork.com/ab/flservices/cl/api/public/org/424346616820252673) and I'll do this porting in 3-4 days. I'm not sure I'll be able to cover the whole Polygon.io API but at least the first public version will provide the same feature set as the current `PolygonDataClient` and `PolygonStreamingClient` classes.

**Comment by jeffwlandry** [comment]
@OlegRa 
Thank you for this useful reply.  I asked jack bell at polygon.io (Jack.bell@polygonio-intercom-mail.com I think) a similar question.  He sounded interested and asked me for the link to the github project.  I suggest you attempt to contact him directly.  I originally got to him via the intercom support link on the polygon.io dashboard.

Unfortunately, I am generally lazy and prefer using other's code.  I am also more adept as losing money in the market than making it, so I am going to have to pass on your hiring suggestion.

I looked at the api a few months back and there are a number of things I found confusing.  Mostly surrounding how you  send and receive the data and do the formatting and object conversion.  Do you take questions?

Thanks again, I appreciate the work you have done.  If I ever do make any of this work I will try to remember you.

Jeff

**Comment by OlegRa** [comment]
@jeffwlandry Feel free to ask any questions about this SDK here on GitHub or in Alpaca Slack (I've just added the [#dev-net](https://alpaca-community.slack.com/archives/C01NXLG96EN) channel to the Alpaca workspace).

If I'll have any news related to Polygon.io client development for .NET I share it with you here.

**Comment by jeffwlandry** [comment]
Thank you, I'll close this for now.
