### ISSUE TITLE
Consider using const for default page size

### ISSUE THREAD

**Issue by gjtorikian** [alpacahq/alpaca-trade-api-csharp#341]
I noticed in this line, a hardcoded value of 10,000 is being used:

https://github.com/alpacahq/alpaca-trade-api-csharp/blob/14e405b704f22997eef44c49a4e9d1644fafd4fd/Alpaca.Markets.Extensions/Pagination/AlpacaDataClientExtensions.cs#L135

This hsould probably be set to the `MAX_PAGE` value, or some other default const. I would make a PR but I haven't got time at the moment!

**Comment by gjtorikian** [comment]
Actually, one other thing occurred to me. In this block of code:

```csharp
foreach (var item in response.Items)
                {
                    yield return item;
                }
```
 
 It seems to me an inflexible design, to have the enumerator return each individual item one by one, rather than the whole set of 10,000 items. Would you be open to changing this?
 
 That is, I think it should be `yield return response.Items`, rather than each item one-by-one. Admittedly, this is for my needs: I want to iterate over all the pages of results, but not each item specifically.

**Comment by OlegRa** [comment]
@gjtorikian It's hard to cover ALL use cases in the single SDK without maintenance nightmare. In most cases, users want to get all items as a single 'stream' via `IEnumerable<T>` or `IAsyncEnumerable<T>` interface. And it's the main reason why this extension method implemented in this way.

So I suggest you just copy-paste this simple extension method into your codebase and change it according to your requirements. If you want you can share your implementation in PR but this should be a full bunch of new methods not a backward-incompatible change of existing methods. Return value change is most annoying for existing users and again - current behavior is expected by most users.

Maybe I'll add such methods soon - it's not a big problem. The real problem is a good name pattern for them :)

And about page size - in fact, this const already exists in the codebase. I have a better idea of how to handle this issue. So I'll change it and this fix will be included in the upcoming releases.

**Comment by gjtorikian** [comment]
I was curious, considering these methods have been added in the 5.0.x branch, whether a minor release could be made to make them public?

Thanks as always for your quick work. ❤️

**Comment by OlegRa** [comment]
The last 2 commits are mostly cosmetic changes - the real functional changes already available in 5.0.3 SDK/Extension packages.

**Comment by gjtorikian** [comment]
Even `GetHistoricalTradesPagesAsAsyncEnumerable`?

**Comment by OlegRa** [comment]
You can always check it using FuGet: [AlpacaDataClientExtensions](https://www.fuget.org/packages/Alpaca.Markets.Extensions/5.0.3/lib/netstandard2.1/Alpaca.Markets.Extensions.dll/Alpaca.Markets.Extensions/AlpacaDataClientExtensions)

**Comment by gjtorikian** [comment]
Ah, I see what's happening. I'm on `5.1.0-alpha2`, but these were incorporated in just 5.0.3:

![image](https://user-images.githubusercontent.com/64050/123488987-f85f2700-d608-11eb-9c21-9ab81da7f17e.png)

Anyway--thank you. I can jump to 5.0.3. Not sure if this is a problem with the release management but just FYI!

**Comment by OlegRa** [comment]
If you need a stable version without bugs with all actual updates/fixes - please, use the 'stable' SDK versions. Right now it's 5.0.x stream. The 5.1.0 contains updated streaming that's not tested well and can potentially contain bugs/performance issues.
And, please, close this issue as soon as you've completed with new functions testing.
