### ISSUE TITLE
Incomplete BracketOrder Support

### ISSUE THREAD

**Issue by AdsophicSolutions** [alpacahq/alpaca-trade-api-csharp#378]
BracketOrder is missing static methods like those available in other Order classes like StopLimitOrder to create a new instance.

**Comment by OlegRa** [comment]
You should use the `Bracket` factory method of the `SimpleOrderBase` class for constructing this class instance. In fact, only the `Market` class instance can be safely used as a source of the `BracketOrder` class creation.

```cs
// The bracket order with the too leg's orders - limit and stop limit
await client.PostOrderAsync(OrderSide.Buy.Market("SPY", 100).Bracket(301M, 299M, 298.5M));

// The bracket order with the too leg's orders - limit and stop
await client.PostOrderAsync(OrderSide.Buy.Market("SPY", 100).Bracket(301M, 299M);
```

You can see examples of OCO, OTO, and bracket orders creation on the [Wiki](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Order-Placement#advanced-oder-types) page.

The current design of bracket orders support is not perfect but it's a compromise between different approaches that I've tried. What are the alternative approaches:

1. Create the static factory method `Bracket` with 4 or 5 parameters. It's something that you expect but I dislike methods with such a big list of arguments. Even 3 arguments of the same type used in the current approach look not ideal for me. But you can always add such an extensions method in your own code if you prefer this approach. Or maybe I'll add it into the extensions package but definitely not into the main SDK.
2. Because we already have the `StopLoss` and `TakeProfit` factory methods we can create the `Bracket` method factory that takes the results of these two methods and creates the new order. But in this case, you are unable to use the fluent approach for creating a bracket order instance because you have to create a source order first, create two legs orders and combine all 3 of them into a single order. Moreover, in this case, this `Bracket` factory method should check that both take profit and stop-loss orders use the same source order and this will be a runtime check (not a C#/.NET way to solve problems).
3. The clearest approach is to allow 'chain' the `StopLossOrder` and `TakeProfitOrder` classes and transform them into the `BracketOrder` class using the fluent interface. It would be harder to implement but I hope the final code will be more clear. The main disadvantage of this approach is that in this case, you'll not see the `Bracket` word in your code :)

**Comment by OlegRa** [comment]
I'll think about 3rd option a little bit and maybe will add it as an additional approach into the SDK. And maybe I'll add the 1st option too into the extensions package.

@AdsophicSolutions Please, don't close this issue. I'll track my changes related to new factory methods here.

**Comment by AdsophicSolutions** [comment]
Thanks for the explanation. I can create bracket orders now.
