### ISSUE TITLE
Upgrading package Alpaca.Markets from 5.1.1 to 5.1.2 contains breaking change

### ISSUE THREAD

**Issue by ManfredLange** [alpacahq/alpaca-trade-api-csharp#395]
I just upgraded nuget package `Alpaca.Markets` from version 5.1.1 to version 5.1.2. This change also changed the type of property `IBar.Volume` from `ulong` to `decimal`.

Here is the metadata extracted from version 5.1.1 (additional comment from me):

```c#
#region Assembly Alpaca.Markets, Version=5.1.1.0, Culture=neutral, PublicKeyToken=16fb7a27ac3b9689
// Alpaca.Markets.dll
#endregion

#nullable enable

using System;

namespace Alpaca.Markets
{
   [CLSCompliant(false)]
   public interface IBar
   {
      string Symbol { get; }
      DateTime TimeUtc { get; }
      decimal Open { get; }
      decimal High { get; }
      decimal Low { get; }
      decimal Close { get; }
      ulong Volume { get; } // <==== type was 'ulong'
      decimal Vwap { get; }
      ulong TradeCount { get; }
   }
}
```

Here is the metadata extracted from version 5.1.2 (additional comment from me):

```c#
#region Assembly Alpaca.Markets, Version=5.1.2.2, Culture=neutral, PublicKeyToken=16fb7a27ac3b9689
// Alpaca.Markets.dll
#endregion

#nullable enable

using System;

namespace Alpaca.Markets
{
   [CLSCompliant(false)]
   public interface IBar
   {
      string Symbol { get; }
      DateTime TimeUtc { get; }
      decimal Open { get; }
      decimal High { get; }
      decimal Low { get; }
      decimal Close { get; }
      decimal Volume { get; } // <==== type now is 'decimal'
      decimal Vwap { get; }
      ulong TradeCount { get; }
   }
}
```

While I believe this is a good change, patch level releases should not contain breaking changes. I am assuming here, that you are following semantic versioning rules (see https://semver.org/).

I'd like to suggest and ask, then going forward you change the major version number when introducing breaking changes. Or if the intention is to provide just a patch, e.g., for fixing a bug, that such a patch level release does not contain breaking changes.

While semantic versioning is just a convention, it is a useful convention that helps getting some indication as to what kind of changes to expect from a new version compared to the version currently in use.

In this case the problem was spotted and mitigated with a combination of different techniques, which I share here in case this may be something others might find helpful, too.

- Wrap all Alpaca apis with dedicated classes. This reduces the "blast radius" in that you will need to make code changes in very few places only.
- Have a good suite of automated tests. This helps spotting differences in behavior (if any).
- Make upgrading nuget packages a dedicated commit for your own source code. This allows reverting the upgrade, if there are too many required code changes.

**Comment by OlegRa** [comment]
The `PublicApiAnalyzer` helps a lot in detecting API changes but of course, it doesn't enforce semantic versioning rules on release. So sometimes I just forget about changes made since the last release and do not change the version properly. The proper test suite approach has the same problem. I can easily refactor tests during development and just forget about incompatible changes at the moment of release preparation. Of course, tests can reference API not as a project but as a package, and in this case, incompatibility will not be visible during the development. And in fact, I have such tests in a separate repo. But this test project has a problem of "egg and chicken" - I'm unable to verify backward compatibility without publishing packages. The package validation analyzer can verify backward compatibility without publishing the package upfront and that's a reason why I really want to add it into the development process of this SDK.

And now about major/minor version changes. I know about the default semantic versioning rule for incompatible changes. But following this rule leads to the version 'inflation' and makes support/maintenance much harder. In fact, many users still work with 4.x versions of SDK and I'll provide fixes for this line for months. If I'll change the major version on each incompatible change it will make my support process a nightmare. It can work if you provide support only for the latest version but I'm sure many users prefer stability over novelty. Maybe in the future, I'll change my mind but now my rules for the version changes are:

- Change major version only on merging the `develop` branch into the `master` branch. All versions produced from the `develop` branch should have alpha, beta, or RC statuses (and related postfixes).
- Change minor version on incompatible changes related to underlying Alpaca API changes or bug fixes.
- Change the revision number in case of any bug fixes or backward-compatible changes (new API introductions).
