### ISSUE TITLE
[QUESTION]: How to handle Rate Limit Exceeded Exception?

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

I am using the latest prerelease version and I have rarely got this exception and not sure how to handle it or what is causing it.

```cs
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
rate limit exceeded

Exception StackTrace:
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at Alpaca.Markets.AlpacaTradingClient.ListOrdersAsync(ListOrdersRequest request, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.CancelOpenOrders(OrderSide orderSide, Boolean onlyPrevDay, String symbol) in D:\Code Projects\OoplesFinanceAdminClient\AlpacaApi.cs:line 2077
```

**Comment by OlegRa** [comment]
@ooples You can expect this type of error from any REST API call. Maybe, it would be better to generate another type of exception in this case (something more strongly-typed) but it will break the backward compatibility.

The SDK has some code that tries to handle REST API calls-per-minute limit semi-automatically. In fact, the `ThrottleParameters` class has default implementation but you can customize it for your needs (increase timeouts and a number of retry attempts).

But it's just a partial workaround for the problem. The real solution depends on your application and should include 2 aspects - decrease the number of API calls and throttle with calls for enforcing limits on the client-side. And this throttling can be simple or more complex and use different priorities for a different types of calls.

But again, I'm not sure that it's a good idea to include it into the SDK because the selected approach will heavily depend on your application/algorithm.

**Comment by ooples** [comment]
I was doing some testing and besides the data streaming subscription, I'm only doing api calls 6 times each time a stock is bought or sold which isn't that often and I did some testing for one of the portfolios and it was barely making any api calls each minute. From what I understand you are limited to 200 api calls per account per minute so unless I'm missing something then it seems like it is limiting me by ip and not by account. Also is the data streaming for subscriptions included in the 200 count?

**Comment by OlegRa** [comment]
Unfortunately, I'm unable to provide you with the full information. Again, I'm not an Alpaca employee and I don't have access to all details about their API. AFAIR they are applying rate limits for all 'trading' calls at the user/IP level. But I'm not sure how they treat cases if you do a lot of requests from the same IP but with different credentials. I think it's better to ask Alpaca support directly about this case.

**Comment by ooples** [comment]
@OlegRa I also wanted to know what is the difference between this error and the Too Many Requests error?

**Comment by OlegRa** [comment]
@ooples In fact it's the same thing. Sometimes API sends just an empty HTTP 429 response code and SDK uses a generic error message (Too Many Requests) for the exception. But sometimes (in most cases in fact) the HTTP response contains the error payload with the error message text - in this case, SDK uses the more specific exception error message from the deserialized payload.
