### ISSUE TITLE
[FEATURE]: Utilizing indicator calculations with a separate api

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I have written a public api for calculating indicators using the alpaca C# api and I was hoping to talk to you about developing it further for future use with the alpaca api. I have emailed you an example project and the library itself. I have over 700+ indicators including 150+ moving averages but for the sake of simplicity I have only included a few so you can get a good idea of how my api works. I was hoping for your honest feedback since this will be my first published api and I know you have plenty of previous experience of course.

**Comment by OlegRa** [comment]
@ooples I'll check your code this weekend and provide my feedback.

**Comment by ooples** [comment]
@OlegRa Now that my library is complete with over 750 indicators, do you think it is ready to include with the alpaca c# sdk as an addon?

**Comment by OlegRa** [comment]
@ooples How do you want to **include** your work into SDK? I see the next options:

1. Create an example that demonstrates how to use your package with data returned by Alpaca SDK. You can prepare such a sample and make PR that I'll review and merge.
2. Add your library as a dependency into the Extensions package and provide helper methods for easy use of any indicator with data provided by the main SDK package. Again - you can prepare a PR or just fill and issue with this proposal and I'll do it for myself.

The first option is easy and if you'll prepare such a PR I'll be glad to review/merge it and support this code in the future. The second option is harder - at least your package should not depend on the `Alpaca.Markets` package, because instead I'll have a circular reference and it will make my maintenance nightmare. In any case, I'll maintain this integration in the future so I want to make this process simpler as much as possible.

I'll try to find time this weekend to check out the latest version of your code and run a static analysis on it again. I'll open PRs with fixes if needed and maybe I'll open some issues about other changes related to code/design that will make integration simpler.

**Comment by ooples** [comment]
I created a pull request with an example showing some of the many features
my indicator library has and how easy it is to use. Let me know if I need
to do anything else
