### ISSUE TITLE
[QUESTION]: Sample code provided returns "Unauthorides Request" when trying to use Functions (eg GetClockAsync)

### ISSUE THREAD

**Issue by DomDom3333** [alpacahq/alpaca-trade-api-csharp#436]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What is your question?

Hi. Not sure if this qualifies as a bug or not since i can't find other people having this issue. When i copy the Sample code from the front page of this repo and provide it with ID and Secret, i get the following error when trying to call client.GetClockAsync():

`Alpaca.Markets.RestClientErrorException: request is not authorized
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at AlpacaExample.Program.Main() in /home/dominik/Documents/GitHub/TradeBot/Program.cs:line 20
   at AlpacaExample.Program.<Main>()`

I've tried the Envirometns.Paper as well as the Live version and both provide me with that error. I've also tried a few other functions to see if it was just the clock but all other Get functions i have tried result in the same error. 

I've tried this on 2 different computers both running Ubuntu based Linux and using Jetbrains Rider as the IDE. 

Thanks for any and all help on this.

Merry Christmas 
Dominik

**Comment by DomDom3333** [comment]
Ok. Apparently im stupid. I used the OAuthApps Id and secret and not the API ones. I am now curious what the OAuth Apps are for then but hey. At least it seems to be working now.

**Comment by OlegRa** [comment]
@DomDom3333 The OAuth is useful in case if you make some apps available for 3rd parties. Or if you don't want to share your secret id and key via code. See more information in [Alpaca documentation](https://alpaca.markets/docs/build-apps_services-with-alpaca/oauth-guide/#how-to-use-polygon-with-oauth). In .NET SDK you just replace the `SecretKey` class with the `OAuthKey` class and all other code will be the same.

**Comment by tdhatcher** [comment]
Unpleasant developer experience is all I can say. The marketing of Alpaca is great and sounds like it can do so much.... but jeesh I still haven't been able to do anything very useful yet after nearly 5 hours.

I've lost several hours making no progress on something so trivial such as authenticating.

I too spent a few hours wondering what the heck I was doing incorrectly with client auth configuration. In the Alpaca UI Dashboard there needs to be a menu item in the UI for "API Settings" so it stands out next to the OAuth Apps menu item!

After exploring the Alpaca UI Dashboard I had just concluded "well OAuth with client_credentials must be how it connects" and mistakenly using the ClientId and ClientSecret.

That is until I found myself googling and then on some random documentation page several layers deep in the Alpaca site that states on the overview page is where you find the API key Id and Secret (https://alpaca.markets/learn/connect-to-alpaca-api)

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/360359/167267685-a65195df-0bed-4edd-b58f-c0648966f871.png">

Okay so I finally have the correct credentials and now I should be sailing.... well not.

I avoid trying this through C#/.NET and go direct with postman after forking the workspace (ie. https://www.postman.com/alpacamarkets)

Set my environment correctly and try using the broker api clock --- and 403 forbidden. Nothing works.
Next I try the trader api clock -- and instead of 403 I get a 401 (an improvement but this should work!)
Next I try the market data api and hit the endpoint /v2/stocks/VOO/quotes .... 200

Okay now I'm ready to go back to C#/.NET and I update my aspnet core application... I setup up with IAlpacaTradingClient and IAlpacaDataClient.

And still, I'm getting 401 with the trading client just to hit the /v2/clock endpoint. I can fetch the quote with 200 which the data doesn't look right. And then see there is a method for IAlpacaDataClient.ListExchangesAsync() and wham "endpoint not found"

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/360359/167268435-ccc1661c-636b-49ea-960f-f33169d065f0.png">

What is going on here? Why does nothing work?
