### ISSUE TITLE
[BUG]: Orders are being cancelled but status doesn't change

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the order flow you recommended where if I see a sell signal then I cancel the open order and send an email with an order cancellation then in the order status event handler submit the actual sell order. I'm getting occasional days where a particular symbol gets cancelled repeatedly every few seconds

### Expected Behavior

I'm only sending an email when an order is cancelled and accepted by the api so order should only be cancelled the one time

### Steps To Reproduce

I can send you an email with my current software but all you need to know is that this doesn't happen super often. Maybe once every few days and below is code that I use to confirm if the order was cancelled then send out the email

```cs
var isDeleted = await alpacaTradingClient.DeleteOrderAsync(order.OrderId).ConfigureAwait(false);

if (isDeleted)
{
    await SendOrderCancellationEmail().ConfigureAwait(false);
}
```

### Environment

- SDK Version: 
- OS (version, bitness): 
- .NET SDK (version):
- target process .NET version/bitness:

**Comment by OlegRa** [comment]
In fact, this method just returns `true` if the underlying HTTP request ended with an HTTP status code between 200 and 299 (HTTP success codes range). So nothing complex and most probably the `true` value is a result of some problem on the server-side. I have some questions related to this issue:

1. Do you call this code snipped several times with the same order ID? If so it would be nice to check why this happened. Ideally, you shouldn't try to cancel an order more than once.
2. If you try to cancel an already canceled order HTTP status should be 422 and the method should return a `false` value. If it's not happened the problem is definitely on the server not on the client.

Unfortunately, Alpaca doesn't provide the order transactions history via API so we are unable to check the order actions log from the client-side. I suggest you to log all order actions along with order statuses for investigating this issue.

**Comment by ooples** [comment]
I am using the same order id info which means it should be returning false
if the order was cancelled already. I contacted the alpaca team about this
first but they said they didn't see any errors on their side so they said
to open a ticket for the issue. I will try your suggestion and include more
logging with my code to give you more information about this issue

Franklin
