### ISSUE TITLE
[QUESTION]:  using the streaming feature in a datagridview 

### ISSUE THREAD

**Issue by jeonnagroup2** [alpacahq/alpaca-trade-api-csharp#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

My course in C# was a long time ago and many things have change since then !!  it's work well in console app but when i try to use it with a datagridview . 

do you have any demo or idea to look for ?

**Comment by ooples** [comment]
I can try to help you out. What exactly are you trying to do with the datagridview?

**Comment by jeonnagroup2** [comment]
Just an example of how to use the "streaming" instead of calling the API each second ! 


My datagrid atm 
![image](https://user-images.githubusercontent.com/91985268/153294641-9ee1b0c0-5fe0-4c6a-82af-26e884009eb2.png)

and the code behind ! 
![image](https://user-images.githubusercontent.com/91985268/153294853-3b473a67-2c08-4a1b-9ee8-6000c24003f0.png)

**Comment by jeonnagroup2** [comment]
i'm alittle rusty in c# , i did my course in 2010 and never really work in that field but i restarted to code few months ago !

**Comment by ooples** [comment]
A couple of things stick out to me immediately. First off you are using async code without using it in async method which is a big no no. Also you aren't properly utilizing the async code that you are using correctly. Also how are you calculating your indicators? I only ask because I run the largest C# indicator library and you can message me for more info. 

Replace this line:
public void UpdateRowScore()

with:
public async Task UpdateRowScore()

Replace this line:
var snapshot = client.GetSnapshotAsync(symbol);

with:
var snapshot = await client.GetSnapshotAsync(symbol).ConfigureAwait(false);

Those are the most obvious things. Then you wouldn't need to keep accessing the result of each item and your code will be fully asynchronous because right now it isn't. As far as helping you get a "streaming" functionality it would require looking at your source code to see how your project workflow is and that would be for a later time

**Comment by jeonnagroup2** [comment]
Ty buddy !! aprreciate the lookup , the "scoring" is an idea of mine using many indicators !! 
i buid this so far !! 

i will make the change you suggest me and like i said C# is far in my head !! 


![image](https://user-images.githubusercontent.com/91985268/153304231-f1f1c740-2a4c-43b7-aeb1-bdb67f416e38.png)

**Comment by ooples** [comment]
I believe this question is outside the scope of this project but I would be happy to help you out. You can message me @cheatcountry on telegram if you want or by email at cheatcountry@gmail.com

**Comment by ooples** [comment]
@OlegRa You can close this issue. I helped him out with his issue
