### ISSUE TITLE
[QUESTION]: 

### ISSUE THREAD

**Issue by tcj2001** [alpacahq/alpaca-trade-api-csharp#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

How to sell a fraction of Crypto Asset as Limit Order

I have .02 BTCUSD in the account

I used
symbol = "BTCUSD"
extendedHours=false;
qty = .01;
limitPrice = 41200;
timeInForce = TimeInForce.Day;

order = await alpacaTradingClient.PostOrderAsync(
LimitOrder.Sell(symbol, qty, limitPrice)
.WithDuration(timeInForce)
.WithExtendedHours(extendedHours), 
token);

This API call need qty as long, it wont accept decimals

**Comment by ooples** [comment]
@tcj2001 Just send me a message on telegram @cheatcountry if you have further questions about this api because you can't keep asking variations of the same question. Here is code below that does what you are asking for

`await alpacaTradingClient.PostOrderAsync(new NewOrderRequest("BTCUSD", OrderQuantity.Fractional(quantity), OrderSide.Sell, OrderType.Limit, TimeInForce.Day) { ExtendedHours = true }).ConfigureAwait(false);`

**Comment by tcj2001** [comment]
Got it
