### ISSUE TITLE
[FEATURE]: Change order quantities to use OrderQuantity instead

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

General inconsistencies with how quantity is handled in all order requests and other order methods

### Describe the solution you'd like

I would love to see this simple change that would help users who I know have asked me about this. Either change the quantity in all order requests and other related classes to use OrderQuantity instead to allow users to set their own quantity such as fractional vs integer or add it as a separate option. I would prefer the former of course

**Comment by OlegRa** [comment]
@ooples I can easily add support for the `OrderQuantity` type into constructor and factory/extension methods due to implicit conversion existence. Technically speaking it's a breaking change but only on a binary level - the compiler will handle it easily without significant code changes. Changing the type of the `Quantity` property is a source-level breaking change and I should think about possible consequences of such change. Or at least provide a way for hot fixing the existing code using some backward-compatible property like `IntegerQuantity`. In any case, it's not something that I'll do immediately - I need some time for analysis.

**Comment by ooples** [comment]
@OlegRa Thanks I know this would make things much easier in the long run

**Comment by OlegRa** [comment]
@ooples The `Quantity` property type changed for all helper order types in 5.3.x and 6.0.x versions. Please, test these changes and close this issue if you are OK with it.
