### ISSUE TITLE
[BUG]: still experiencing the connect and authenticate issues

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I saw that it was fixed for the release version so I may just use that but I am using just the alpaca.markets.extensions in my project with the latest prerelease version and I'm still experiencing the issue where it hangs at the connect and authenticate line

### Environment

```markdown
- SDK Version: 
- OS (version, bitness): 
- .NET SDK (version):
- target process .NET version/bitness:
```

**Comment by OlegRa** [comment]
@ooples It's expected behavior for implicit dependency. The Extensions NuGet package is always published with the **minimal supported** main SDK version number in the `references` table. It means that it is compatible with any version of the main SDK that is equal to or greater than this specified version number. I strongly recommend you reference both main and Extensions packages and use the proper combination of versions of both packages. It makes dependencies management a little bit harder but in this case, you can control the situation better.
