### ISSUE TITLE
Can we get a working HelloWorld? Poor developer experience lacking Getting Started guide and Documentation / SDK out of sync

### ISSUE THREAD

**Issue by tdhatcher** [alpacahq/alpaca-trade-api-csharp#507]
@DomDom3333 The OAuth is useful in case if you make some apps available for 3rd parties. Or if you don't want to share your secret id and key via code. See more information in [Alpaca documentation](https://alpaca.markets/docs/build-apps_services-with-alpaca/oauth-guide/#how-to-use-polygon-with-oauth). In .NET SDK you just replace the `SecretKey` class with the `OAuthKey` class and all other code will be the same.

_Originally posted by @OlegRa in https://github.com/alpacahq/alpaca-trade-api-csharp/issues/436#issuecomment-1001131200_

Unpleasant developer experience is all I can say. The marketing website of Alpaca is great and sounds like it can do so much.... but jeesh I still haven't been able to do anything very useful yet after nearly 5 hours and a lot of:

401 "request is not authorized"
403 "forbidden"
404 "endpoint not found."

I've lost several hours making no progress on something so trivial such as authenticating.

I too spent a few hours wondering what the heck I was doing incorrectly with my C#/.NET client auth configuration. In the Alpaca UI Dashboard there needs to be a menu item in the UI for "API Access" so it stands out next to the OAuth Apps menu item!

After exploring the Alpaca UI Dashboard I had just concluded "well OAuth with client_credentials must be how it connects" and mistakenly using the ClientId and ClientSecret.

That is until I found myself googling and then on some random documentation page several layers deep in the Alpaca site that states on the overview page is where you find the API key Id and Secret (https://alpaca.markets/learn/connect-to-alpaca-api)

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/360359/167267685-a65195df-0bed-4edd-b58f-c0648966f871.png">

Okay so I finally have the correct credentials and now I should be sailing.... well no.

I decided to avoid trying this through C#/.NET and go direct with postman after forking the workspace (ie. https://www.postman.com/alpacamarkets)

Set my environment correctly and try using the broker api clock --- and 403 forbidden. Still nothing works.

Next I try the trader api clock -- and instead of 403 I get a 401 (an improvement but I expected a success 200!)

<img width="385" alt="image" src="https://user-images.githubusercontent.com/360359/167268902-dfd02d6b-1bec-4a70-842a-4fb941e505f7.png">

Next I try the market data api and hit the endpoint /v2/stocks/VOO/quotes .... 200 to my amazement.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/360359/167268975-db3bff83-a5a4-4e0c-b666-61f4694dc9fc.png">

Okay now I'm ready to go back to C#/.NET and I update my aspnet core application... I setup up with IAlpacaTradingClient and IAlpacaDataClient.

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/360359/167268909-511c8ec0-a44a-4836-837b-eb6466e4a074.png">

And still, I'm getting 401 with the trading client just to hit the /v2/clock endpoint. I can fetch the quote with 200. I explore a bit and see there is a method for IAlpacaDataClient.ListExchangesAsync() and wham "endpoint not found". Why is the SDK accessing an endpoint that doesn't exist?

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/360359/167268435-ccc1661c-636b-49ea-960f-f33169d065f0.png">

What is going on here? Why does very little work? Makes it pretty difficult to view this as a reliable platform with this initial experience. There needs to be some focus on getting developers off the ground and running with some documentation improvements. A sandbox should not have limitations if that is what is behind all this 403 nonsense.

Based on the marketing website I thought this would be a well polished experience... far from it. I decided to try this out before Interactive Brokers after narrowing it down to these 2 platforms to explore for programmatic transactions and brokerage services. Alpaca seemed better at the time.

**Comment by tdhatcher** [comment]
I left out I was using version 5.3.1 of the nuget packages for both Alpaca.Markets and Alpaca.Markets.Extensions

I did try bumping the package references to preview 6.0.3-rc1 and then couldn't get even as far as I did with 5.3.1 due to httpclient issues as part of dependency injection configuration which are details encapsulated by the Alpaca.Markets.Extensions 

https://www.nuget.org/packages/Alpaca.Markets/

**Comment by OlegRa** [comment]
@tdhatcher Thanks a lot for your detailed feedback. I'll try to summarize your problems and answer some questions:

1. It's not clear how to obtain authorization data on the Alpaca site. I think it's a general Alpaca documentation problem and it would be better if you'll report it as a separate issue on [this](https://github.com/alpacahq/Alpaca-API/issues) or [this](https://github.com/alpacahq/alpaca-docs/issues) repo. From my side, I'll try to write a more detailed explanation (with code examples) on [this Wiki page](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Authentication-Types) and add a link to this page into the README.md file.
2. It's not clear which `SecretKey` implementation should be used for both types of authentication. If you have a better idea of how to design it from the .NET/C# perspective I'll be glad to hear your proposal. Again, I'll try to make the related Wiki page more useful and explain it in more detail.
3. Looks like you've incorrectly used the [Broker API Postman collection](https://www.postman.com/alpacamarkets/workspace/alpaca-public-workspace/documentation/17430392-aabd1790-d917-4afb-be20-5b36c0edbbe2) for your testing (Set my environment correctly and try using the Broker API clock --- and 403 forbidden. Still nothing works.) instead of [Market v2 Data API](https://www.postman.com/alpacamarkets/workspace/alpaca-public-workspace/documentation/17430392-c7175945-d81d-49fe-8f2e-6b6550b9974a) collection. Again, this problem has no relation to the SDK itself and should be reported as a documentation issue (IMO).
4. The `ListExchangesAsync` problem. I'll check it right now and if the URL preparation logic was broken I fix it and prepare an updated version for all affected packages.
5. The problem with the latest 6.0.3-rc1 version. Please, open the separate issue and provide more details about your problem. It's not clear from your last comment what exactly goes wrong and why all works fine for the 5.3.1 because I don't see too many differences in the NuGet dependencies graph between these two versions.

Please, add any issues that I've missed from your long posts to this list. But please don't mix Alpaca documentation issues and SDK issues. And if you have ideas on how to make good HowTo I can assign you an issue #23 - I'm not a technical writer so any help in this area is very appreciated!

**Comment by OlegRa** [comment]
@tdhatcher Update - I've created separate issue #508 about the `ListExchangesAsync` (and 2 other metadata-related methods) problems.

**Comment by tdhatcher** [comment]
@OlegRa thanks for the response. I suspect a few of the issues I ran into related to 403 status aren't specific to the .NET/C# SDK but it's hard to diagnose at first whether that is the case. I was reading some documentation earlier today and found another buried nuget of helpful information.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/360359/167314906-649a3a0f-d27d-48d2-90a5-da6d068070c4.png">

I'd say in general the Alpaca developer onboarding experience needs a bit of work. As a newcomer to the platform you are kind of left with no clear learning path so where to start isn't exactly clear and what prerequisites are required. Or what capabilities your account has.

Just another example how a newcomer needs to read different disjointed articles to try and piece the puzzle together. Half way through the article you encounter critical prerequisite action.

https://alpaca.markets/learn/generating-alpaca-api-client-in-3-easy-steps-with-the-openapi-generator/
<img width="670" alt="image" src="https://user-images.githubusercontent.com/360359/167314264-5412b145-dd16-4b2c-9a03-c1903c577bd7.png">

I will try to keep fiddling with it and trying to work through issues I encounter and try to document. And will contribute whatever I can if I can get things working.

But seems like there are three areas where issues arise: Account/API Documentation, Postman workspace, and .NET/C# SDK

**Comment by tdhatcher** [comment]
The kind of experience looks consistent for other newcomers. Here's a post in the forum "Forbidden Here. Forbidden There."

https://forum.alpaca.markets/t/forbidden-here-forbidden-there/7255/3

**Comment by OlegRa** [comment]
@tdhatcher Could you please provide more information about issue number 5 in my list (the problem with the latest 6.0.3-rc1 version)?
