### ISSUE TITLE
Change calendar open/close times from DateTime to TimeStamp

### ISSUE THREAD

**Issue by ttt733** [alpacahq/alpaca-trade-api-csharp#52]
I think it would be more correct for the open/close values in a calendar response, e.g.
```
{
  "date": "2018-01-03",
  "open": "09:30",
  "close": "16:00"
}
```
to be interpreted as TimeSpans rather than DateTimes, as they are converted to DateTimes using default values for year/month/day, which usually wind up being wrong. We could do that by implementing a custom TimeSpan converter, like this - https://stackoverflow.com/a/52504446. Alternatively, we could leave them as DateTimes and find a way to pass in the date field as well, but I'm not sure if that's workable with the way converters are done field-by-field.

The current solution to this issue is doing something like this, which I'm not a big fan of:
```
var calendars = restClient.ListCalendarAsync(DateTime.Today).Result;
var calendarDate = calendars.First().TradingDate;
var closingTime = calendars.First().TradingCloseTime;
closingTime = new DateTime(calendarDate.Year, calendarDate.Month, calendarDate.Day, closingTime.Hour, closingTime.Minute, closingTime.Second);
```

**Comment by OlegRa** [comment]
@ttt733 If you will check [JsonCalendar.OnDeserializeMethod](https://github.com/alpacahq/alpaca-trade-api-csharp/blob/0ba9ea251b90d7bd8118faa914340a494ba1ab0a/Alpaca.Markets/Messages/JsonCalendar.cs#L22) implementation you can see that it tries to convert this time offset values into correct `DateTime` values.
Unfortunately, API returns these date and time values not in UTC time zone but in EST timezone instead. All other time stamps in API use UTC time zone and I've tried to convert these values into UTC too. But I've made a mistake in my initial implementation. This problem fixed in my last commit. You can review these simple changes [here](https://github.com/alpacahq/alpaca-trade-api-csharp/commit/2a1a6fdcb3a7b86dff07ffdca88e35d13c7fde59).
Please, test how well it works now - all `DateTime` fields should return correct UTC timestamps.

**Comment by OlegRa** [comment]
@ttt733 Please, re-check and close it if problem is not actual now.

**Comment by OlegRa** [comment]
@ttt733 I'll close it for now. If problem still exists just re-open it.
