### ISSUE TITLE
[FEATURE]: add support for account update stream

### ISSUE THREAD

**Issue by oriagranat9** [alpacahq/alpaca-trade-api-csharp#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

i want to be able to receive account updates via web sockets instead of having to query the http endpoint

### Describe the solution you'd like

inside the AlpacaStreamingClient have the ability to subscribe to the account updates stream, and handle the incoming messages from that stream the same way it is handled for trades update (with a different message parse) 

### Describe alternatives you've considered

querying the http endpoint every interval, less efficient and increases delays.

**Comment by OlegRa** [comment]
@oriagranat9 I see that you've already reported this issue using the Alpaca [forum](https://forum.alpaca.markets/) and it's good. I also recommend you duplicate the same request using the special issues-only [repository](https://github.com/alpacahq/Alpaca-API/issues) created for server-side feature requests and error reporting.

Unfortunately, I'm unable to add to the client SDK anything that's not supported by the server-side. The old version of the Alpaca trading stream support account updates but this feature is now disabled and removed from the server. AFAIU, it creates too much workload because you have to re-calculate open P&L data on each trade. 

But why do you need to re-request account data on time interval? Just request it on each trade update provided by the existing stream and calculate client-side P&L values using the latest data stream subscription data. It should be enough for most use cases.
