### ISSUE TITLE
[BUG]: Alpaca.Markets.RestClientErrorException: invalid syntax error when attempting to subscribe with alpaca crypto streaming client

### ISSUE THREAD

**Issue by jharonfe** [alpacahq/alpaca-trade-api-csharp#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the `Paper.GetAlpacaCryptoStreamingClient` successfully connects and authenticates, the code creates several subscription objects for quotes, trades, and minute bars for a set of crypto symbols, such as `BTCUSD`. Once all the subscriptions are created the `SubscribeAsync` command is called to execute the subscriptions. However the `OnError` event handler raises a `RestClientErrorException` with the message `invalid syntax`. 

After this error the socket remains open. However no quote, trade, or bar events are ever received. It appears the subscription request was not correctly registered as the error message would suggest.

### Expected Behavior

Expected behavior is to successfully register these market data subscriptions and begin receiving event data in response.

### Environment

```markdown
- SDK Version: Alpaca.Markets v6.1.5
- OS (version, bitness): Ubuntu 18.04
- .NET SDK (version): 6.0.102
```

### Anything else?

The alpaca dotnet api does not encounter a similar error for equity data. Also when testing using the python and node alpaca apis, am able to subscribe to crypto data without issue. This issue has only appeared with the dotnet api, and only for crypto data not equity data.

**Comment by OlegRa** [comment]
At first view, it looks like issue #385 resurrection. But it can be also just a duplicate for #557 and I strongly believe it is.

@jharonfe the first thing that you have to check is the crypto symbols notation. The 6.1.4 and later NuGet packages use the new `v1beta2` version of Alpaca Crypto API for both REST and WS endpoints. See more information in the #557 issue thread. This version of the underlying API uses slash-based crypto-pair names like `BTC/USD` instead of the old `BTCUSD` one. I'm not sure about Python and NodeJS SDKs but maybe they just use the old versions of endpoints.

If naming is not an issue you can try the next workarounds related to the subscription process itself:

- Explicitly await each subscription completion not just by awaiting the `SubscribeAsync` call but also by awaiting the `OnSubscribedChanged` event of this `IAlpacaDataSubscription` object. The main disadvantage of this approach is that it will make your overall subscription time longer and convert the async process into a mostly sync sequence of call-wait actions.
- Use the `Alpaca.Market.Extensions` NuGet package and special extensions methods that allow you subscribe to several `IAlpacaDataSubscription` objects in one call.

**Comment by jharonfe** [comment]
@OlegRa, I tested your suggestion of using the `BTC/USD` in place of `BTCUSD` and that solved the issue ! The `invalid syntax` error does not occur and I am receiving event data as expected. 

Thanks for the feedback and the quick turnaround. Pardon I was not aware the crypto identifiers are represented differently in the dotnet api.
