### ISSUE TITLE
Overflow exception on Time Conversion from Unix for all quotes received

### ISSUE THREAD

**Issue by Ronmenator** [alpacahq/alpaca-trade-api-csharp#66]
Receiving Quotes from Nats messages are throwing an exception in 3.0.4. See attached images

![image](https://user-images.githubusercontent.com/6628234/59687415-acfc1d80-9191-11e9-9794-93e5fdbc611a.png)

![image](https://user-images.githubusercontent.com/6628234/59687503-b2f1fe80-9191-11e9-9165-45f337120179.png)

**Comment by sghitch** [comment]
I started seeing this last week, looks like the timestamp started coming in nanoseconds, but only for quotes so far

**Comment by Ronmenator** [comment]
So the fix should be very easy to divide the timestamp by 1000000, to get rid of the nanoseconds before doing the time conversion.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sghitch** [comment]
That's what I've done to get myself unblocked. For a more formal fix ideally you'd add some of the extra ticks to at least get 100 nanosecond precision

**Comment by Ronmenator** [comment]
Agree,

I will implement this on my branch and test it out.

Thanks for the reply

**Comment by OlegRa** [comment]
@Ronmenator I'll assign it to you because right now I'm on vacation and unable to properly code this fix but I'll try to find time for PR review. Just don't forget about all target .NET profiles.

@ttt733 Trevor, please check this issue with Polygon.io API - according to their documentation all timestamps in NATS streams should be in Unix milliseconds format.

**Comment by OlegRa** [comment]
@Ronmenator Please test it using version [3.0.6](https://www.nuget.org/packages/Alpaca.Markets/3.0.6) and re-open if problem still exists.
