### ISSUE TITLE
[BUG]: Tutorial does not work

### ISSUE THREAD

**Issue by AntoineDubois** [alpacahq/alpaca-trade-api-csharp#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I follow carefully the officiel tutorial [Here](https://github.com/alpacahq/alpaca-trade-api-csharp/tree/develop)
Unfortunately, `dotnet run` returns the following error: 
`Unhandled exception. Alpaca.Markets.RestClientErrorException: request is not authorized`
The Alpaca’s python API works perfectly fine to me though.

### Expected Behavior

I expect the tutorial not succeed.

### Steps To Reproduce

Follow the steps of the tutorial [Here](https://github.com/alpacahq/alpaca-trade-api-csharp/tree/develop)

### Environment

- SDK Version: 
- OS (version, bitness):  MAC M1
- .NET SDK (version): 7.0.100
- target process .NET version/bitness:

**Comment by OlegRa** [comment]
@AntoineDubois I've tested the latest stable version of `Alpaca.Markets` NuGet package (6.2.4 right now) on Windows, Linux, and MacOS using the different .NET SDKs and everything works fine for me. I follow the instructions (written by me years ago of course) and replace empty strings with proper API key/secret values for the _paper_ trading environment.

On MacOS I've used the latest .NET 7.0.400 SDK but there are not too many differences between 7.0.100 and 7.0.400 releases. Please, check that you use the valid active API key/secret for the paper environment in the C# code. If you're able to connect the _paper_ environment from the Python SDK but unable to do the same from the .NET - please, share your Python code snippet (ideally the same clock information requesting sample) here so I'll be able to investigate it further.

**Comment by AntoineDubois** [comment]
Thank you Oleg for your quick reply :)
My Python code comes from the tutorial.

`import json
import alpaca_trade_api as tradeapi

with open("../credentials.txt") as f:
    credentials = f.read()
credentials = json.loads(credentials)

api = tradeapi.REST(key_id = credentials["key_id"], secret_key = credentials["secret_key"], base_url = "https://api.alpaca.markets")

# Get our account information.
account = api.get_account()

# Check if our account is restricted from trading.
if account.trading_blocked:
    print('Account is currently restricted from trading.')

# Check how much money we can use to open new positions.
print('${} is available as buying power.'.format(account.buying_power))

# Check our current balance vs. our balance at the last market close
balance_change = float(account.equity) - float(account.last_equity)
print(f'Today\'s portfolio balance change: ${balance_change}')

api.close()`

**Comment by OlegRa** [comment]
@AntoineDubois, according to your code you try to connect a Live environment using the `base_url = "https://api.alpaca.markets"` setting in the Python SDK. But the .NET SDK example uses the Paper environment `Environments.Paper` because I assume that if you write a sample code you are still not ready to trade with real money :)

Maybe I should state it more explicitly in the README file. Or you can propose changes for this simple How-To tutorial in the form of PR. I try to maintain a [Wiki](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki) with up-to-date information about current SDK use cases. You can read more about Live and Paper environment handling in .NET SDK [here](https://github.com/alpacahq/alpaca-trade-api-csharp/wiki/Environments-Handling).

And of course, the simplest way to switch is to change these lines:

```cs
var client = Environments.Paper
    .GetAlpacaTradingClient(new SecretKey(KEY_ID, SECRET_KEY));
```

in sample code using another built-in environment:

```cs
var client = Environments.Live
    .GetAlpacaTradingClient(new SecretKey(KEY_ID, SECRET_KEY));
```

All other code will work as before and I hope you'll be able to move forward with the .NET SDK and Alpaca.

**Comment by AntoineDubois** [comment]
By the force of desperation, I generated new credentials. Environment.Paper worked !
Environment.Live still does not work for me.
Thank you very much Oleg!

**Comment by OlegRa** [comment]
@AntoineDubois, good news for Paper users but I have to check Live as well on my side. I'll do it later because right now I don't have access to Live credentials right now.

**Comment by OlegRa** [comment]
Live works for me as well, so I'll close it for now. @AntoineDubois, if you still have issues with connectivity - just re-open this issue and provide more information.
