### ISSUE TITLE
[BUG]: Single line using disposes HTTP request before it is used

### ISSUE THREAD

**Issue by artemiusgreat** [alpacahq/alpaca-trade-api-csharp#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Connecting to trading client the same way as shown in the [example](https://github.com/alpacahq/alpaca-trade-api-csharp/blob/develop/UsageExamples/MeanReversionWithCrypto.cs) 
Then, trying to request any information from it, tried methods `tradeClient.GetAssetAsync` and `tradeClient.GetAccountAsync`, the result is the same, exception `Variable value is not available because the module is optimized. Click the drop down for options.`. 

![image](https://github.com/alpacahq/alpaca-trade-api-csharp/assets/5140879/bdf4f53c-95cd-4a0f-b80a-959ea72ff7b8)

Couldn't find a lot in google or github issues but after trying to debug the API library, it seems to get stuck [here](https://github.com/alpacahq/alpaca-trade-api-csharp/blob/7e8f76c6f07e2c05eaa4427e869f962ecfa0a8f2/Alpaca.Markets/Helpers/HttpClientExtensions.cs#L82). 
Which looks like variable `request` is being disposed by optimizer before it is actually used.

![image](https://github.com/alpacahq/alpaca-trade-api-csharp/assets/5140879/bd7c7933-d100-4c1c-8c5a-6a00d07db670)

### Expected Behavior

Perhaps, using multiline scoped `using` would be more reliable. 

```
using (var request = ...) 
{
   return callAndDeserialize(...);
}
```

instead of 

```
using (var request = ...); 
return callAndDeserialize(...);
```

### Environment

```markdown
- SDK Version: 7.0.4
- OS (version, bitness): Windows 11, x64
- .NET SDK (version): .NET Core 7.0
- target process .NET version/bitness: x64
```

### Anything else?

After thinking about this code, I'm not even sure if `HttpRequestMessage` really needs to be disposed. 
Response may contain stream but disposing request seems unnecessary.

**Comment by OlegRa** [comment]
@artemiusgreat Yes, the NuGet package contains a release build with all optimizations applied and I think it's the best option for most use cases.

Exception handling settings in Visual Studio allows you to catch exceptions at the place where they are thrown, not just in your code, and most probably it's a root cause of this "unexpected" behavior. But you can always write your try/catch block and set a breakpoint inside to examine the real exception details.

The `RestClientErrorException` contains not only the original HTTP error code but also the Alpaca error code and message if they are provided in response.
